version: 0.2

phases:
  install:
    commands:
      - docker pull postgres:12.0
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - echo Building docker image
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker images
      - echo pushing docker image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"postgres","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - printf '%s' $REPOSITORY_URI:$IMAGE_TAG > imagename.txt
#      - cat imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
    - imagename.txt